# This is a basic workflow to help you get started with Actions

name: RepoChecker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Repo checker
      uses: VegetableGarden/melon@0.0.1
      with:
        # your expected repo to run customized command
        expected-repo: melon-skip
        # eg. git status
        command: |
          chmod +x ./echo.sh
          ./echo.sh

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: melon
        author_email: melon@github.com
        message: "Add change"
        add: "*.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
